package deltaanalytics.gui.bruker.measuresample;

import deltaanalytics.user.entity.User;
import javafx.geometry.Insets;
import javafx.scene.control.*;
import javafx.scene.layout.GridPane;

public class StartMeasurementDialog {
    void showNeuDialog() {
        // Create the custom dialog.
        Dialog<Void> dialog = new Dialog<>();
        dialog.setTitle("Start Measurement");
        dialog.setHeaderText("Configuration overview");


        ButtonType loginButtonType = new ButtonType("Next", ButtonBar.ButtonData.OK_DONE);
        dialog.getDialogPane().getButtonTypes().addAll(loginButtonType, ButtonType.CANCEL);

        GridPane grid = new GridPane();

        grid.setHgap(10);
        grid.setVgap(10);
        grid.setPadding(new Insets(20, 150, 10, 10));

        Label labelADP = new Label("ADP");
        grid.add(labelADP, 0, 0);
        TextField textFieldADP = new TextField();
        grid.add(textFieldADP, 1, 0);
        Label labelADT = new Label("ADT");
        grid.add(labelADT, 0, 1);
        TextField textFieldADT = new TextField();
        grid.add(textFieldADT, 1, 1);
        Label labelAPF = new Label("APF");
        grid.add(labelAPF, 0, 2);
        TextField textFieldAPF = new TextField();
        grid.add(textFieldAPF, 1, 2);
        Label labelAPT = new Label("APT");
        grid.add(labelAPT, 0, 3);
        TextField textFieldAPT = new TextField();
        grid.add(textFieldAPT, 1, 3);
        Label labelAQM = new Label("AQM");
        grid.add(labelAQM, 0, 4);
        TextField textFieldAQM = new TextField();
        grid.add(textFieldAQM, 1, 4);
        Label labelBMS = new Label("BMS");
        grid.add(labelBMS, 0, 5);
        TextField textFieldBMS = new TextField();
        grid.add(textFieldBMS, 1, 5);
        Label labelBSF = new Label("BSF");
        grid.add(labelBSF, 0, 6);
        TextField textFieldBSF = new TextField();
        grid.add(textFieldBSF, 1, 6);
        Label labelCHN = new Label("CHN");
        grid.add(labelCHN, 0, 7);
        TextField textFieldCHN = new TextField();
        grid.add(textFieldCHN, 1, 7);
        Label labelCNM = new Label("CNM");
        grid.add(labelCNM, 0, 8);
        TextField textFieldCNM = new TextField();
        grid.add(textFieldCNM, 1, 8);
        Label labelCOF = new Label("COF");
        grid.add(labelCOF, 0, 9);
        TextField textFieldCOF = new TextField();
        grid.add(textFieldCOF, 1, 9);
        Label labelDAP = new Label("DAP");
        grid.add(labelDAP, 0, 10);
        TextField textFieldDAP = new TextField();
        grid.add(textFieldDAP, 1, 10);
        Label labelDEL = new Label("DEL");
        grid.add(labelDEL, 0, 11);
        TextField textFieldDEL = new TextField();
        grid.add(textFieldDEL, 1, 11);
        Label labelDIG = new Label("DIG");
        grid.add(labelDIG, 0, 12);
        TextField textFieldDIG = new TextField();
        grid.add(textFieldDIG, 1, 12);
        Label labelDLY = new Label("DLY");
        grid.add(labelDLY, 0, 13);
        TextField textFieldDLY = new TextField();
        grid.add(textFieldDLY, 1, 13);
        Label labelDMX = new Label("DMX");
        grid.add(labelDMX, 0, 14);
        TextField textFieldDMX = new TextField();
        grid.add(textFieldDMX, 1, 14);
        Label labelDPA = new Label("DPA");
        grid.add(labelDPA, 0, 15);
        TextField textFieldDPA = new TextField();
        grid.add(textFieldDPA, 1, 15);
        Label labelDPO = new Label("DPO");
        grid.add(labelDPO, 0, 16);
        TextField textFieldDPO = new TextField();
        grid.add(textFieldDPO, 1, 16);
        Label labelDTC = new Label("DTC");
        grid.add(labelDTC, 0, 17);
        TextField textFieldDTC = new TextField();
        grid.add(textFieldDTC, 1, 17);
        Label labelEXP = new Label("EXP");
        grid.add(labelEXP, 0, 18);
        TextField textFieldEXP = new TextField();
        grid.add(textFieldEXP, 1, 18);
        Label labelGSG = new Label("GSG");
        grid.add(labelGSG, 0, 19);
        TextField textFieldGSG = new TextField();
        grid.add(textFieldGSG, 1, 19);
        Label labelHFQ = new Label("HFQ");
        grid.add(labelHFQ, 0, 20);
        TextField textFieldHFQ = new TextField();
        grid.add(textFieldHFQ, 1, 20);
        Label labelHFW = new Label("HFW");
        grid.add(labelHFW, 0, 21);
        TextField textFieldHFW = new TextField();
        grid.add(textFieldHFW, 1, 21);
        Label labelIRS = new Label("IRS");
        grid.add(labelIRS, 0, 22);
        TextField textFieldIRS = new TextField();
        grid.add(textFieldIRS, 1, 22);
        Label labelHPF = new Label("HPF");
        grid.add(labelHPF, 0, 23);
        TextField textFieldHPF = new TextField();
        grid.add(textFieldHPF, 1, 23);
        Label labelLFQ = new Label("LFQ");
        grid.add(labelLFQ, 0, 24);
        TextField textFieldLFQ = new TextField();
        grid.add(textFieldLFQ, 1, 24);
        Label labelLFW = new Label("LFW");
        grid.add(labelLFW, 0, 25);
        TextField textFieldLFW = new TextField();
        grid.add(textFieldLFW, 1, 25);
        Label labelLPF = new Label("LPF");
        grid.add(labelLPF, 0, 26);
        TextField textFieldLPF = new TextField();
        grid.add(textFieldLPF, 1, 26);
        Label labelMIN = new Label("MIN");
        grid.add(labelMIN, 0, 27);
        TextField textFieldMIN = new TextField();
        grid.add(textFieldMIN, 1, 27);
        Label labelMIR = new Label("MIR");
        grid.add(labelMIR, 0, 28);
        TextField textFieldMIR = new TextField();
        grid.add(textFieldMIR, 1, 28);
        Label labelNAM = new Label("NAM");
        grid.add(labelNAM, 0, 29);
        TextField textFieldNAM = new TextField();
        grid.add(textFieldNAM, 1, 29);
        Label labelNLI = new Label("NLI");
        grid.add(labelNLI, 0, 30);
        TextField textFieldNLI = new TextField();
        grid.add(textFieldNLI, 1, 30);
        Label labelNSS = new Label("NSS");
        grid.add(labelNSS, 0, 31);
        TextField textFieldNSS = new TextField();
        grid.add(textFieldNSS, 1, 31);
        Label labelNSR = new Label("NSR");
        grid.add(labelNSR, 0, 32);
        TextField textFieldNSR = new TextField();
        grid.add(textFieldNSR, 1, 32);
        Label labelOEX = new Label("OEX");
        grid.add(labelOEX, 0, 33);
        TextField textFieldOEX = new TextField();
        grid.add(textFieldOEX, 1, 33);
        Label labelOPF = new Label("OPF");
        grid.add(labelOPF, 0, 34);
        TextField textFieldOPF = new TextField();
        grid.add(textFieldOPF, 1, 34);
        Label labelPGN = new Label("PGN");
        grid.add(labelPGN, 0, 35);
        TextField textFieldPGN = new TextField();
        grid.add(textFieldPGN, 1, 35);
        Label labelPGR = new Label("PGR");
        grid.add(labelPGR, 0, 36);
        TextField textFieldPGR = new TextField();
        grid.add(textFieldPGR, 1, 36);
        Label labelPHR = new Label("PHR");
        grid.add(labelPHR, 0, 37);
        TextField textFieldPHR = new TextField();
        grid.add(textFieldPHR, 1, 37);
        Label labelPHZ = new Label("PHZ");
        grid.add(labelPHZ, 0, 38);
        TextField textFieldPHZ = new TextField();
        grid.add(textFieldPHZ, 1, 38);
        Label labelPLF = new Label("PLF");
        grid.add(labelPLF, 0, 39);
        TextField textFieldPLF = new TextField();
        grid.add(textFieldPLF, 1, 39);
        Label labelPTH = new Label("PTH");
        grid.add(labelPTH, 0, 40);
        TextField textFieldPTH = new TextField();
        grid.add(textFieldPTH, 1, 40);
        Label labelRCH = new Label("RCH");
        grid.add(labelRCH, 0, 41);
        TextField textFieldRCH = new TextField();
        grid.add(textFieldRCH, 1, 41);
        Label labelRES = new Label("RES");
        grid.add(labelRES, 0, 42);
        TextField textFieldRES = new TextField();
        grid.add(textFieldRES, 1, 42);
        Label labelRGN = new Label("RGN");
        grid.add(labelRGN, 0, 43);
        TextField textFieldRGN = new TextField();
        grid.add(textFieldRGN, 1, 43);
        Label labelSAN = new Label("SAN");
        grid.add(labelSAN, 0, 44);
        TextField textFieldSAN = new TextField();
        grid.add(textFieldSAN, 1, 44);
        Label labelSEP = new Label("SEP");
        grid.add(labelSEP, 0, 45);
        TextField textFieldSEP = new TextField();
        grid.add(textFieldSEP, 1, 45);
        Label labelSFM = new Label("SFM");
        grid.add(labelSFM, 0, 46);
        TextField textFieldSFM = new TextField();
        grid.add(textFieldSFM, 1, 46);
        Label labelSGN = new Label("SGN");
        grid.add(labelSGN, 0, 47);
        TextField textFieldSGN = new TextField();
        grid.add(textFieldSGN, 1, 47);
        Label labelSNM = new Label("SNM");
        grid.add(labelSNM, 0, 48);
        TextField textFieldSNM = new TextField();
        grid.add(textFieldSNM, 1, 48);
        Label labelSON = new Label("SON");
        grid.add(labelSON, 0, 49);
        TextField textFieldSON = new TextField();
        grid.add(textFieldSON, 1, 49);
        Label labelVEL = new Label("VEL");
        grid.add(labelVEL, 0, 50);
        TextField textFieldVEL = new TextField();
        grid.add(textFieldVEL, 1, 50);
        Label labelX64 = new Label("X64");
        grid.add(labelX64, 0, 51);
        TextField textFieldX64 = new TextField();
        grid.add(textFieldX64, 1, 51);
        Label labelXPP = new Label("XPP");
        grid.add(labelXPP, 0, 52);
        TextField textFieldXPP = new TextField();
        grid.add(textFieldXPP, 1, 52);
        Label labelYON = new Label("YON");
        grid.add(labelYON, 0, 53);
        TextField textFieldYON = new TextField();
        grid.add(textFieldYON, 1, 53);
        Label labelZFF = new Label("ZFF");
        grid.add(labelZFF, 0, 54);
        TextField textFieldZFF = new TextField();
        grid.add(textFieldZFF, 1, 54);

        dialog.getDialogPane().setContent(new ScrollPane(grid));
        dialog.showAndWait();
    }
}
